model_config:
  num_historical_steps: 11
  num_future_steps: 80
  use_intention: true
  token_size: 2048
  mode: train
  predictor: smart
  dataset: waymo
  input_dim: 2
  hidden_dim: 128
  output_dim: 2
  output_head: false
  num_heads: 8
  head_dim: 16
  dropout: 0.1
  num_freq_bands: 64
  lr: 0.0005
  warmup_steps: 0
  total_steps: 32
  use_smart_tokens: true
  use_mala: true
  inference: true
  lr_scheduler: cosine
  decoder:
    num_historical_steps: 11
    num_future_steps: 80
    use_intention: true
    token_size: 2048
    num_map_layers: 3
    num_agent_layers: 6
    a2a_radius: 60
    pl2pl_radius: 10
    pl2a_radius: 30
    time_span: 30
